const users = [
    {
        "id":"1",
        "name":"ronak",
        "email":"ronakjoshi24499@gmail.com",
        "password":"rnk@123",
        "lastname":"joshi",
        "cart":[],
        "history":[],
        "role":false,
        "isAuth":true
    },
    {
        "id":"2",
        "name":"sharath",
        "email":"sharath@gmail.com",
        "password":"sharath@123",
        "lastname":"k.p.",
        "cart":[],
        "history":[],
        "role":false,
        "isAuth":true
    },
    {
        "id":"3",
        "name":"jainesh",
        "email":"jainesh@gmail.com",
        "password":"jainesh@123",
        "lastname":"jain",
        "cart":[],
        "history":[],
        "role":true,
        "isAuth":true
    },
    {
        "id":"4",
        "name":"abhishek",
        "email":"abhishek@gmail.com",
        "password":"abhishek@123",
        "lastname":"doshi",
        "cart":[],
        "history":[],
        "role":true,
        "isAuth":false
    }
]
export default users;